baseurl: ""
url: "http://private.nickvorobiov.com"
markdown: kramdown
exclude:
  - node_modules
  - package.json
  - README.md
  - gulpfile.js
metrika: 38223835
google_analytics: UA-46456269-13
permalink: /:title/

title: "Научу знакомиться и строить близкие отношения с женщинами за 8 занятий"
description: "Личные тренировки с Николаем Воробьёвым"
#keywords: "#ШоуВоробьёва"
author: "Николай Воробьёв"
