baseurl: ""
url: "http://nickvorobiov.com"
markdown: kramdown
exclude:
  - node_modules
  - package.json
  - README.md
  - gulpfile.js
#metrika: 36255245
#google_analytics: UA-46456269-10
permalink: /:title/

#title: "Николай Воробьёв"
#description: "Помогаю перестать быть такой жалкой тряпкой"
#keywords: "#ШоуВоробьёва"
#author: "Николай Воробьёв"
